from __future__ import annotations

from datetime import datetime
from typing import Protocol

from oris_sdk.gene import Gene, StoreQuery, SyncLogEntry


class StoreProtocol(Protocol):
    def close(self) -> None: ...
    def save(self, gene: Gene) -> None: ...
    def get(self, gene_id: str) -> Gene | None: ...
    def delete(self, gene_id: str) -> None: ...
    def query(self, q: StoreQuery) -> list[Gene]: ...
    def update_stats(self, gene_id: str, used: bool, success: bool) -> None: ...
    def list_genes(self, limit: int = 50, offset: int = 0) -> list[Gene]: ...
    def get_unsynced(self) -> list[Gene]: ...
    def mark_synced(self, gene_id: str, synced_at: datetime) -> None: ...
    def log_sync(self, entry: SyncLogEntry) -> None: ...
    def get_sync_log(self, limit: int = 50) -> list[SyncLogEntry]: ...
